First pass at the REST endpoints for roles.
getgort/gort pull request #20
Opened 2021-06-20 21:07 UTC by theothertomelliott

Couple of outstanding questions:
* Should we error out for bundles and permissions that currently don't exists?
* Should the role permissions endpoints account for bundle versions?

2021-06-21 15:47 UTC, clockworksoul commented on dataaccess/interface.go
> +	RoleExists(ctx context.Context, rolename string) (bool, error)
Good catch.

2021-06-21 15:50 UTC, clockworksoul commented on service/group-handlers_test.go
> +func TestGrantGroupRole(t *testing.T) {
Tests, yay!!

2021-06-21 16:09 UTC, clockworksoul requested changes
The only nit is the `jsonRequest` function name, but otherwise everything looks good!

2021-06-21 16:10 UTC, clockworksoul commented
Oh, also, while you're in there, would you mind incrementing the version to `0.7.5-dev.0` ?

2021-06-22 00:50 UTC, theothertomelliott commented on service/service_test.go
> +func jsonRequest(t *testing.T, router *mux.Router, method string, target string, body interface{}, out interface{}) int {
Refactored as discussed.

2021-06-22 15:15 UTC, merged